// Generated from 웨딩홀 정보.xlsx (Master_60)
window.WEDDING_HALLS = [
  {
    "id": 1,
    "name": "아펠가모 광화문",
    "district": "종로구",
    "address": "서울 종로구 종로1길 50",
    "hallType": "컨벤션",
    "hallTone": "밝은홀",
    "ceremonyType": "분리",
    "ceremonyTime": "90",
    "hallCount": 1,
    "menu": "뷔페",
    "mealPrice": 110000,
    "mealStartPrice": 85000,
    "mealAveragePrice": 110000,
    "mealRange": "85000~110000",
    "minimumGuarantee": 300,
    "maxCapacity": 550,
    "rentPrice": 6500000,
    "baseRentPrice": 6500000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://apelgamo.com/home/wedding3",
    "naverMap": "https://map.naver.com/v5/search/아펠가모%20광화문",
    "memo": "공식 페이지 / 식대는 플랫폼 참고",
    "zone": "기타",
    "tags": "채플감성/단정",
    "budgetBand": "~2.5억",
    "recommendationGrade": "C",
    "recommendationScore": "2.85"
  },
  {
    "id": 2,
    "name": "HW컨벤션센터",
    "district": "종로구",
    "address": "서울 종로구 자하문로 255",
    "hallType": "컨벤션",
    "hallTone": "혼합",
    "ceremonyType": "분리",
    "ceremonyTime": "120",
    "hallCount": 3,
    "menu": "뷔페",
    "mealPrice": 109000,
    "mealStartPrice": 130000,
    "mealAveragePrice": 109000,
    "mealRange": "89000~130000",
    "minimumGuarantee": 200,
    "maxCapacity": 800,
    "rentPrice": 13000000,
    "baseRentPrice": 17000000,
    "minimumRentPrice": 13000000,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "",
    "subwayAccess": "#VALUE!",
    "homepage": "",
    "naverMap": "https://map.naver.com/v5/search/HW컨벤션센터",
    "memo": "주소만 반영",
    "zone": "기타",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 5,
    "name": "성균관컨벤션웨딩홀",
    "district": "종로구",
    "address": "서울 종로구 성균관로 31",
    "hallType": "컨벤션",
    "hallTone": "어두운홀",
    "ceremonyType": "분리",
    "ceremonyTime": "90",
    "hallCount": 1,
    "menu": "뷔페",
    "mealPrice": 75000,
    "mealStartPrice": 75000,
    "mealAveragePrice": 75000,
    "mealRange": "75000",
    "minimumGuarantee": 200,
    "maxCapacity": 500,
    "rentPrice": 8350000,
    "baseRentPrice": 8350000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "",
    "subwayAccess": "#VALUE!",
    "homepage": "",
    "naverMap": "https://map.naver.com/v5/search/성균관컨벤션웨딩홀",
    "memo": "주소만 반영",
    "zone": "기타",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 6,
    "name": "SW컨벤션센터",
    "district": "종로구",
    "address": "서울 종로구 지봉로 19",
    "hallType": "컨벤션",
    "hallTone": "어두운홀",
    "ceremonyType": "분리",
    "ceremonyTime": "70",
    "hallCount": 1,
    "menu": "뷔페",
    "mealPrice": 70000,
    "mealStartPrice": 70000,
    "mealAveragePrice": 70000,
    "mealRange": "70000",
    "minimumGuarantee": 200,
    "maxCapacity": 800,
    "rentPrice": 6000000,
    "baseRentPrice": 6000000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "",
    "subwayAccess": "#VALUE!",
    "homepage": "",
    "naverMap": "https://map.naver.com/v5/search/SW컨벤션센터",
    "memo": "주소만 반영",
    "zone": "기타",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 8,
    "name": "라루체",
    "district": "중구",
    "address": "서울 중구 퇴계로18길 46",
    "hallType": "하우스",
    "hallTone": "밝은홀",
    "ceremonyType": "분리",
    "ceremonyTime": "120",
    "hallCount": 2,
    "menu": "뷔페",
    "mealPrice": 110000,
    "mealStartPrice": 110000,
    "mealAveragePrice": 110000,
    "mealRange": "110000",
    "minimumGuarantee": 200,
    "maxCapacity": 1500,
    "rentPrice": 15000000,
    "baseRentPrice": 15000000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://www.lalucewedding.co.kr/",
    "naverMap": "https://map.naver.com/v5/search/라루체",
    "memo": "공식 사이트 확인",
    "zone": "기타",
    "tags": "하우스/야외감성",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 10,
    "name": "루이비스컨벤션",
    "district": "중구",
    "address": "서울 중구 청파로 463",
    "hallType": "컨벤션",
    "hallTone": "어두운홀",
    "ceremonyType": "분리",
    "ceremonyTime": "70",
    "hallCount": 1,
    "menu": "뷔페",
    "mealPrice": 87000,
    "mealStartPrice": 87000,
    "mealAveragePrice": 87000,
    "mealRange": "87000",
    "minimumGuarantee": 300,
    "maxCapacity": 800,
    "rentPrice": 9500000,
    "baseRentPrice": 9500000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://lvconvention.co.kr/main.html",
    "naverMap": "https://map.naver.com/v5/search/루이비스컨벤션",
    "memo": "공식 사이트 확인",
    "zone": "기타",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 13,
    "name": "틸티드 한남",
    "district": "용산구",
    "address": "서울 용산구 한남대로 150-10",
    "hallType": "하우스",
    "hallTone": "밝은홀",
    "ceremonyType": "동시",
    "ceremonyTime": "360",
    "hallCount": 1,
    "menu": "양식",
    "mealPrice": 98000,
    "mealStartPrice": 98000,
    "mealAveragePrice": 98000,
    "mealRange": "98000",
    "minimumGuarantee": 120,
    "maxCapacity": 300,
    "rentPrice": 5500000,
    "baseRentPrice": 5500000,
    "minimumRentPrice": null,
    "stylingPrice": 9800000,
    "flowerPrice": null,
    "parking": "",
    "subwayAccess": "9619300300",
    "homepage": "",
    "naverMap": "https://map.naver.com/v5/search/틸티드%20한남",
    "memo": "소규모 후보",
    "zone": "기타",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "C",
    "recommendationScore": "2.8"
  },
  {
    "id": 18,
    "name": "디노체컨벤션웨딩홀",
    "district": "성동구",
    "address": "서울 성동구 왕십리광장로 17",
    "hallType": "컨벤션",
    "hallTone": "어두운홀",
    "ceremonyType": "분리",
    "ceremonyTime": "90",
    "hallCount": 1,
    "menu": "뷔페",
    "mealPrice": 80000,
    "mealStartPrice": 80000,
    "mealAveragePrice": 80000,
    "mealRange": "80000",
    "minimumGuarantee": 200,
    "maxCapacity": 1000,
    "rentPrice": 8000000,
    "baseRentPrice": 8000000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "",
    "subwayAccess": "#VALUE!",
    "homepage": "",
    "naverMap": "https://map.naver.com/v5/search/디노체컨벤션웨딩홀",
    "memo": "주소만 반영",
    "zone": "기타",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 20,
    "name": "스타시티아트홀",
    "district": "광진구",
    "address": "서울 광진구 아차산로 262",
    "hallType": "컨벤션",
    "hallTone": "밝은홀",
    "ceremonyType": "분리",
    "ceremonyTime": "80",
    "hallCount": 1,
    "menu": "한식",
    "mealPrice": 85000,
    "mealStartPrice": 85000,
    "mealAveragePrice": 85000,
    "mealRange": "85000",
    "minimumGuarantee": 250,
    "maxCapacity": 700,
    "rentPrice": 9000000,
    "baseRentPrice": 9000000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://starcityarthall.com/",
    "naverMap": "https://map.naver.com/v5/search/스타시티아트홀",
    "memo": "공식 사이트 확인",
    "zone": "기타",
    "tags": "도심/밝음",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 21,
    "name": "벨라루체웨딩홀 서울점",
    "district": "동대문구",
    "address": "서울 동대문구 망우로 61",
    "hallType": "컨벤션",
    "hallTone": "혼합",
    "ceremonyType": "분리",
    "ceremonyTime": "90",
    "hallCount": 3,
    "menu": "뷔페",
    "mealPrice": 88000,
    "mealStartPrice": 88000,
    "mealAveragePrice": 88000,
    "mealRange": "88000",
    "minimumGuarantee": 200,
    "maxCapacity": 350,
    "rentPrice": 8800000,
    "baseRentPrice": 8800000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://www.bellaluceseoul.co.kr/",
    "naverMap": "https://map.naver.com/v5/search/벨라루체웨딩홀%20서울점",
    "memo": "공식 사이트 확인",
    "zone": "기타",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 23,
    "name": "DMC타워웨딩",
    "district": "마포구",
    "address": "서울 마포구 성암로 189",
    "hallType": "컨벤션",
    "hallTone": "밝은홀",
    "ceremonyType": "분리",
    "ceremonyTime": "90",
    "hallCount": 3,
    "menu": "뷔페",
    "mealPrice": 93000,
    "mealStartPrice": 93000,
    "mealAveragePrice": 93000,
    "mealRange": "93000",
    "minimumGuarantee": 250,
    "maxCapacity": 500,
    "rentPrice": 17000000,
    "baseRentPrice": 17000000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://www.dmcwedding.co.kr/",
    "naverMap": "https://map.naver.com/v5/search/DMC타워웨딩",
    "memo": "공식 사이트 확인",
    "zone": "마포",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 24,
    "name": "월드컵컨벤션",
    "district": "마포구",
    "address": "서울 마포구 월드컵로 240",
    "hallType": "컨벤션",
    "hallTone": "밝은홀",
    "ceremonyType": "분리",
    "ceremonyTime": "90",
    "hallCount": 2,
    "menu": "뷔페",
    "mealPrice": 89000,
    "mealStartPrice": 89000,
    "mealAveragePrice": 89000,
    "mealRange": "89000",
    "minimumGuarantee": 250,
    "maxCapacity": 1200,
    "rentPrice": 8500000,
    "baseRentPrice": 8500000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "",
    "subwayAccess": "#VALUE!",
    "homepage": "",
    "naverMap": "https://map.naver.com/v5/search/월드컵컨벤션",
    "memo": "주소만 반영",
    "zone": "마포",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 25,
    "name": "더파티움 여의도",
    "district": "영등포구",
    "address": "서울 영등포구 은행로 30",
    "hallType": "컨벤션",
    "hallTone": "어두운홀",
    "ceremonyType": "분리",
    "ceremonyTime": "80",
    "hallCount": 2,
    "menu": "한식",
    "mealPrice": 121000,
    "mealStartPrice": 121000,
    "mealAveragePrice": 121000,
    "mealRange": "121000",
    "minimumGuarantee": 300,
    "maxCapacity": 700,
    "rentPrice": 16500000,
    "baseRentPrice": 16500000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "",
    "subwayAccess": "#VALUE!",
    "homepage": "",
    "naverMap": "https://map.naver.com/v5/search/더파티움%20여의도",
    "memo": "주소만 반영",
    "zone": "영등포",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 26,
    "name": "JK아트컨벤션",
    "district": "영등포구",
    "address": "서울 영등포구 문래로 164",
    "hallType": "컨벤션",
    "hallTone": "어두운홀",
    "ceremonyType": "분리",
    "ceremonyTime": "120",
    "hallCount": 3,
    "menu": "뷔페",
    "mealPrice": 86000,
    "mealStartPrice": 86000,
    "mealAveragePrice": 86000,
    "mealRange": "86000",
    "minimumGuarantee": 250,
    "maxCapacity": 800,
    "rentPrice": 11000000,
    "baseRentPrice": 11000000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://www.jkart.co.kr/",
    "naverMap": "https://map.naver.com/v5/search/JK아트컨벤션",
    "memo": "공식 사이트 확인",
    "zone": "영등포",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 27,
    "name": "그랜드컨벤션센터",
    "district": "영등포구",
    "address": "서울 영등포구 양평로 58",
    "hallType": "컨벤션",
    "hallTone": "혼합",
    "ceremonyType": "분리",
    "ceremonyTime": "90",
    "hallCount": 2,
    "menu": "뷔페",
    "mealPrice": 90000,
    "mealStartPrice": 90000,
    "mealAveragePrice": 90000,
    "mealRange": "90000",
    "minimumGuarantee": 250,
    "maxCapacity": 1200,
    "rentPrice": 9500000,
    "baseRentPrice": 9500000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://www.grandconvention.co.kr/",
    "naverMap": "https://map.naver.com/v5/search/그랜드컨벤션센터",
    "memo": "공식 사이트 + 가격 참고",
    "zone": "영등포",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 28,
    "name": "더컨벤션 영등포",
    "district": "영등포구",
    "address": "서울 영등포구 국회대로38길 2",
    "hallType": "컨벤션",
    "hallTone": "어두운홀",
    "ceremonyType": "분리",
    "ceremonyTime": "80",
    "hallCount": 2,
    "menu": "뷔페",
    "mealPrice": 110000,
    "mealStartPrice": 110000,
    "mealAveragePrice": 110000,
    "mealRange": "110000",
    "minimumGuarantee": 300,
    "maxCapacity": 550,
    "rentPrice": 11000000,
    "baseRentPrice": 11000000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "http://theconvention.co.kr/ydp",
    "naverMap": "https://map.naver.com/v5/search/더컨벤션%20영등포",
    "memo": "홀사용료/보증인원 확인",
    "zone": "영등포",
    "tags": "컨벤션/버진로드",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 29,
    "name": "웨딩시티 신도림",
    "district": "구로구",
    "address": "서울 구로구 새말로 97",
    "hallType": "컨벤션",
    "hallTone": "어두운홀",
    "ceremonyType": "분리",
    "ceremonyTime": "80",
    "hallCount": 3,
    "menu": "뷔페",
    "mealPrice": 70000,
    "mealStartPrice": 60000,
    "mealAveragePrice": 70000,
    "mealRange": "60000~80000",
    "minimumGuarantee": 300,
    "maxCapacity": 2200,
    "rentPrice": 8000000,
    "baseRentPrice": 8000000,
    "minimumRentPrice": null,
    "stylingPrice": 300000,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://www.tmwedding.co.kr/",
    "naverMap": "https://map.naver.com/v5/search/웨딩시티%20신도림",
    "memo": "공식 사이트 + 가격 참고",
    "zone": "기타",
    "tags": "가성비/도심",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 30,
    "name": "더세인트",
    "district": "구로구",
    "address": "서울 구로구 경인로 662",
    "hallType": "컨벤션",
    "hallTone": "혼합",
    "ceremonyType": "분리",
    "ceremonyTime": "120",
    "hallCount": 2,
    "menu": "한식/양식",
    "mealPrice": 120000,
    "mealStartPrice": 110000,
    "mealAveragePrice": 120000,
    "mealRange": "110000~130000",
    "minimumGuarantee": 200,
    "maxCapacity": 350,
    "rentPrice": 26000000,
    "baseRentPrice": 26000000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://thesaint.co.kr/",
    "naverMap": "https://map.naver.com/v5/search/더세인트%20신도림",
    "memo": "공식 사이트 확인",
    "zone": "기타",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 31,
    "name": "더뉴컨벤션",
    "district": "강서구",
    "address": "서울 강서구 화곡로 55",
    "hallType": "컨벤션",
    "hallTone": "혼합",
    "ceremonyType": "분리",
    "ceremonyTime": "80",
    "hallCount": 4,
    "menu": "뷔페",
    "mealPrice": 90000,
    "mealStartPrice": 82000,
    "mealAveragePrice": 90000,
    "mealRange": "82000~95000",
    "minimumGuarantee": 200,
    "maxCapacity": 600,
    "rentPrice": 9000000,
    "baseRentPrice": 13000000,
    "minimumRentPrice": 9000000,
    "stylingPrice": 3000000,
    "flowerPrice": null,
    "parking": "",
    "subwayAccess": "#VALUE!",
    "homepage": "",
    "naverMap": "https://map.naver.com/v5/search/더뉴컨벤션",
    "memo": "주소 추정/확인필요",
    "zone": "기타",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 32,
    "name": "엘타워",
    "district": "서초구",
    "address": "서울 서초구 강남대로 213",
    "hallType": "컨벤션",
    "hallTone": "혼합",
    "ceremonyType": "동시",
    "ceremonyTime": "180",
    "hallCount": 3,
    "menu": "한식/양식",
    "mealPrice": 150000,
    "mealStartPrice": 130000,
    "mealAveragePrice": 150000,
    "mealRange": "130000~170000",
    "minimumGuarantee": 250,
    "maxCapacity": 800,
    "rentPrice": 20000000,
    "baseRentPrice": 21000000,
    "minimumRentPrice": 20000000,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://eltower.co.kr/",
    "naverMap": "https://map.naver.com/v5/search/엘타워",
    "memo": "공식 도메인 + 가격 참고",
    "zone": "서초",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 33,
    "name": "더화이트베일",
    "district": "서초구",
    "address": "서울 서초구 서초중앙로 14",
    "hallType": "컨벤션",
    "hallTone": "혼합",
    "ceremonyType": "분리",
    "ceremonyTime": "90",
    "hallCount": 2,
    "menu": "뷔페",
    "mealPrice": 90000,
    "mealStartPrice": 80000,
    "mealAveragePrice": 90000,
    "mealRange": "80000~95000",
    "minimumGuarantee": 250,
    "maxCapacity": 950,
    "rentPrice": 9500000,
    "baseRentPrice": 9500000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://thewhiteveil.co.kr/",
    "naverMap": "https://map.naver.com/v5/search/더화이트베일",
    "memo": "공식 사이트 확인",
    "zone": "서초",
    "tags": "컨벤션/우아",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 34,
    "name": "아펠가모 반포",
    "district": "서초구",
    "address": "서울 서초구 반포대로 235",
    "hallType": "채플",
    "hallTone": "밝은홀",
    "ceremonyType": "분리",
    "ceremonyTime": "90",
    "hallCount": 1,
    "menu": "뷔페",
    "mealPrice": 110000,
    "mealStartPrice": 110000,
    "mealAveragePrice": 110000,
    "mealRange": "110000",
    "minimumGuarantee": 300,
    "maxCapacity": 550,
    "rentPrice": 11000000,
    "baseRentPrice": 11000000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://apelgamo.com/home/wedding2",
    "naverMap": "https://map.naver.com/v5/search/아펠가모%20반포",
    "memo": "공식 지점 확인",
    "zone": "서초",
    "tags": "채플/고전",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 36,
    "name": "노블발렌티 대치",
    "district": "강남구",
    "address": "서울 강남구 영동대로 325",
    "hallType": "채플",
    "hallTone": "밝은홀",
    "ceremonyType": "분리",
    "ceremonyTime": "90",
    "hallCount": 1,
    "menu": "뷔페",
    "mealPrice": 100000,
    "mealStartPrice": 100000,
    "mealAveragePrice": 100000,
    "mealRange": "100000",
    "minimumGuarantee": 300,
    "maxCapacity": 550,
    "rentPrice": 13000000,
    "baseRentPrice": 13000000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://noblevalentidaechi.co.kr/",
    "naverMap": "https://map.naver.com/v5/search/노블발렌티%20대치",
    "memo": "공식 사이트 + 일부 가격 노출",
    "zone": "강남",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 37,
    "name": "노블발렌티 삼성",
    "district": "강남구",
    "address": "서울 강남구 봉은사로 637",
    "hallType": "채플",
    "hallTone": "밝은홀",
    "ceremonyType": "분리",
    "ceremonyTime": "120",
    "hallCount": 1,
    "menu": "양식",
    "mealPrice": 100000,
    "mealStartPrice": 100000,
    "mealAveragePrice": 100000,
    "mealRange": "100000",
    "minimumGuarantee": 300,
    "maxCapacity": 550,
    "rentPrice": 13000000,
    "baseRentPrice": 13000000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://noblevalenti.co.kr/",
    "naverMap": "https://map.naver.com/v5/search/노블발렌티%20삼성",
    "memo": "공식 사이트 확인",
    "zone": "강남",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 38,
    "name": "빌라드지디 청담",
    "district": "강남구",
    "address": "서울 강남구 학동로 519",
    "hallType": "하우스",
    "hallTone": "밝은홀",
    "ceremonyType": "동시",
    "ceremonyTime": "180",
    "hallCount": 1,
    "menu": "양식",
    "mealPrice": 150000,
    "mealStartPrice": 130000,
    "mealAveragePrice": 150000,
    "mealRange": "130000~170000",
    "minimumGuarantee": 270,
    "maxCapacity": 380,
    "rentPrice": 17000000,
    "baseRentPrice": 17000000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": 13000000,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://chungdamvilladegd.com/ ",
    "naverMap": "https://map.naver.com/v5/search/빌라드지디%20청담",
    "memo": "공식 사이트 확인",
    "zone": "강남",
    "tags": "하우스/무드",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 39,
    "name": "빌라드지디 수서",
    "district": "강남구",
    "address": "서울 강남구 밤고개로21길 79",
    "hallType": "하우스",
    "hallTone": "밝은홀",
    "ceremonyType": "분리",
    "ceremonyTime": "150",
    "hallCount": 1,
    "menu": "뷔페",
    "mealPrice": 99000,
    "mealStartPrice": 99000,
    "mealAveragePrice": 99000,
    "mealRange": "99000",
    "minimumGuarantee": 300,
    "maxCapacity": 500,
    "rentPrice": 12000000,
    "baseRentPrice": 12000000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": 8800000,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://suseovilladegd.com/",
    "naverMap": "https://map.naver.com/v5/search/빌라드지디%20수서",
    "memo": "FAQ에서 계약금 300만원 확인",
    "zone": "강남",
    "tags": "가든/유리정원",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 40,
    "name": "더채플앳청담",
    "district": "강남구",
    "address": "서울 강남구 선릉로 757",
    "hallType": "채플",
    "hallTone": "밝은홀",
    "ceremonyType": "분리",
    "ceremonyTime": "90",
    "hallCount": 2,
    "menu": "뷔페",
    "mealPrice": 120000,
    "mealStartPrice": 120000,
    "mealAveragePrice": 120000,
    "mealRange": "120000",
    "minimumGuarantee": 300,
    "maxCapacity": 500,
    "rentPrice": 12000000,
    "baseRentPrice": 12000000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://www.thechapel.co.kr/home/wedding1",
    "naverMap": "https://map.naver.com/v5/search/더채플앳청담",
    "memo": "공식 사이트 확인",
    "zone": "강남",
    "tags": "채플/클래식",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 41,
    "name": "상록아트홀",
    "district": "강남구",
    "address": "서울 강남구 언주로 508 상록회관 5층",
    "hallType": "컨벤션",
    "hallTone": "혼합",
    "ceremonyType": "분리",
    "ceremonyTime": "80",
    "hallCount": 2,
    "menu": "뷔페",
    "mealPrice": 98000,
    "mealStartPrice": 98000,
    "mealAveragePrice": 98000,
    "mealRange": "98000",
    "minimumGuarantee": 250,
    "maxCapacity": 500,
    "rentPrice": 9800000,
    "baseRentPrice": 9800000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://srwedding.co.kr/",
    "naverMap": "https://map.naver.com/v5/search/상록아트홀",
    "memo": "공식 사이트 + 가격 참고",
    "zone": "강남",
    "tags": "호텔식/웅장",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 43,
    "name": "라온제나강남",
    "district": "강남구",
    "address": "서울 강남구 언주로 564 인근",
    "hallType": "복합홀",
    "hallTone": "혼합",
    "ceremonyType": "분리",
    "ceremonyTime": "90",
    "hallCount": 2,
    "menu": "뷔페",
    "mealPrice": 77000,
    "mealStartPrice": 77000,
    "mealAveragePrice": 77000,
    "mealRange": "77000",
    "minimumGuarantee": 250,
    "maxCapacity": 600,
    "rentPrice": 7700000,
    "baseRentPrice": 7700000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://xn--939ao9fob394buxtzvc.com/",
    "naverMap": "https://map.naver.com/v5/search/라온제나강남",
    "memo": "공식 사이트 확인 / 상세주소 재확인",
    "zone": "강남",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 44,
    "name": "샐럽앤어셈",
    "district": "강남구",
    "address": "서울 강남구 선릉로 818",
    "hallType": "하우스",
    "hallTone": "밝은홀",
    "ceremonyType": "분리",
    "ceremonyTime": "90",
    "hallCount": 1,
    "menu": "뷔페",
    "mealPrice": 98000,
    "mealStartPrice": 98000,
    "mealAveragePrice": 98000,
    "mealRange": "98000",
    "minimumGuarantee": 330,
    "maxCapacity": 500,
    "rentPrice": 14500000,
    "baseRentPrice": 14500000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "",
    "subwayAccess": "#VALUE!",
    "homepage": "",
    "naverMap": "https://map.naver.com/v5/search/샐럽앤어셈",
    "memo": "주소 추정/확인필요",
    "zone": "강남",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 45,
    "name": "스카이뷰컨벤션",
    "district": "강남구",
    "address": "서울 강남구 테헤란로 152",
    "hallType": "컨벤션",
    "hallTone": "혼합",
    "ceremonyType": "분리",
    "ceremonyTime": "90",
    "hallCount": 1,
    "menu": "뷔페",
    "mealPrice": 63000,
    "mealStartPrice": 63000,
    "mealAveragePrice": 63000,
    "mealRange": "25000~63000",
    "minimumGuarantee": 250,
    "maxCapacity": 350,
    "rentPrice": 6600000,
    "baseRentPrice": 6600000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "",
    "subwayAccess": "#VALUE!",
    "homepage": "",
    "naverMap": "https://map.naver.com/v5/search/스카이뷰컨벤션",
    "memo": "주소 추정/확인필요",
    "zone": "강남",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 46,
    "name": "더라빌",
    "district": "강남구",
    "address": "서울 강남구 봉은사로 531",
    "hallType": "컨벤션",
    "hallTone": "어두운홀",
    "ceremonyType": "분리",
    "ceremonyTime": "180",
    "hallCount": 2,
    "menu": "양식",
    "mealPrice": 111000,
    "mealStartPrice": 87000,
    "mealAveragePrice": 111000,
    "mealRange": "87000~137000",
    "minimumGuarantee": 200,
    "maxCapacity": 800,
    "rentPrice": 8000000,
    "baseRentPrice": 8000000,
    "minimumRentPrice": null,
    "stylingPrice": 1000000,
    "flowerPrice": 8000000,
    "parking": "",
    "subwayAccess": "#VALUE!",
    "homepage": "",
    "naverMap": "https://map.naver.com/v5/search/더라빌",
    "memo": "주소 추정/확인필요",
    "zone": "강남",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 47,
    "name": "브라이드밸리",
    "district": "강남구",
    "address": "서울 강남구 봉은사로 637",
    "hallType": "컨벤션",
    "hallTone": "밝은홀",
    "ceremonyType": "분리",
    "ceremonyTime": "90",
    "hallCount": 1,
    "menu": "뷔페",
    "mealPrice": 85000,
    "mealStartPrice": 85000,
    "mealAveragePrice": 85000,
    "mealRange": "85000",
    "minimumGuarantee": 250,
    "maxCapacity": 600,
    "rentPrice": 8500000,
    "baseRentPrice": 8500000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "",
    "subwayAccess": "#VALUE!",
    "homepage": "",
    "naverMap": "https://map.naver.com/v5/search/브라이드밸리",
    "memo": "확인필요",
    "zone": "강남",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 48,
    "name": "그랜드힐컨벤션",
    "district": "강남구",
    "address": "서울 강남구 역삼로 607",
    "hallType": "컨벤션",
    "hallTone": "어두운홀",
    "ceremonyType": "동시",
    "ceremonyTime": "180",
    "hallCount": 3,
    "menu": "양식",
    "mealPrice": 119000,
    "mealStartPrice": 99000,
    "mealAveragePrice": 119000,
    "mealRange": "99000~130000",
    "minimumGuarantee": 250,
    "maxCapacity": 360,
    "rentPrice": 12000000,
    "baseRentPrice": 12000000,
    "minimumRentPrice": 12000000,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "",
    "subwayAccess": "#VALUE!",
    "homepage": "",
    "naverMap": "https://map.naver.com/v5/search/그랜드힐컨벤션",
    "memo": "확인필요",
    "zone": "강남",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 49,
    "name": "더청담",
    "district": "강남구",
    "address": "서울 강남구 도산대로 356",
    "hallType": "하우스",
    "hallTone": "밝은홀",
    "ceremonyType": "분리",
    "ceremonyTime": "90",
    "hallCount": 1,
    "menu": "양식",
    "mealPrice": 95000,
    "mealStartPrice": 95000,
    "mealAveragePrice": 95000,
    "mealRange": "95000",
    "minimumGuarantee": 250,
    "maxCapacity": 1000,
    "rentPrice": 9500000,
    "baseRentPrice": 9500000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "",
    "subwayAccess": "#VALUE!",
    "homepage": "",
    "naverMap": "https://map.naver.com/v5/search/더청담",
    "memo": "확인필요",
    "zone": "강남",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 49,
    "name": "더청담",
    "district": "강남구",
    "address": "서울 강남구 도산대로 356",
    "hallType": "하우스",
    "hallTone": "밝은홀",
    "ceremonyType": "동시",
    "ceremonyTime": "300",
    "hallCount": 1,
    "menu": "양식",
    "mealPrice": 95000,
    "mealStartPrice": 95000,
    "mealAveragePrice": 95000,
    "mealRange": "95000",
    "minimumGuarantee": 150,
    "maxCapacity": 200,
    "rentPrice": 11000000,
    "baseRentPrice": 11000000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "",
    "subwayAccess": "#VALUE!",
    "homepage": "",
    "naverMap": "https://map.naver.com/v5/search/더청담",
    "memo": "확인필요",
    "zone": "강남",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 50,
    "name": "트라디노이",
    "district": "강남구",
    "address": "서울 강남구 학동로 519 인근",
    "hallType": "하우스",
    "hallTone": "밝은홀",
    "ceremonyType": "분리",
    "ceremonyTime": "240",
    "hallCount": 1,
    "menu": "뷔페",
    "mealPrice": 98000,
    "mealStartPrice": 98000,
    "mealAveragePrice": 98000,
    "mealRange": "98000",
    "minimumGuarantee": 150,
    "maxCapacity": 250,
    "rentPrice": 5800000,
    "baseRentPrice": 5800000,
    "minimumRentPrice": null,
    "stylingPrice": 1500000,
    "flowerPrice": 3900000,
    "parking": "",
    "subwayAccess": "9611300250",
    "homepage": "",
    "naverMap": "https://map.naver.com/v5/search/트라디노이",
    "memo": "확인필요",
    "zone": "강남",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "C",
    "recommendationScore": "2.8"
  },
  {
    "id": 51,
    "name": "소노펠리체 컨벤션",
    "district": "강남구",
    "address": "서울 강남구 테헤란로87길 22",
    "hallType": "컨벤션",
    "hallTone": "어두운홀",
    "ceremonyType": "분리",
    "ceremonyTime": "120",
    "hallCount": 1,
    "menu": "뷔페",
    "mealPrice": 83000,
    "mealStartPrice": 83000,
    "mealAveragePrice": 83000,
    "mealRange": "83000",
    "minimumGuarantee": 350,
    "maxCapacity": 700,
    "rentPrice": 9000000,
    "baseRentPrice": 9000000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://www.sonofeliceconvention.com/",
    "naverMap": "https://map.naver.com/v5/search/소노펠리체%20컨벤션",
    "memo": "공식 사이트 확인",
    "zone": "강남",
    "tags": "컨벤션/웅장",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 52,
    "name": "아펠가모 잠실",
    "district": "송파구",
    "address": "서울 송파구 올림픽로35길 137",
    "hallType": "컨벤션",
    "hallTone": "혼합",
    "ceremonyType": "분리",
    "ceremonyTime": "90",
    "hallCount": 1,
    "menu": "뷔페",
    "mealPrice": 110000,
    "mealStartPrice": 110000,
    "mealAveragePrice": 110000,
    "mealRange": "110000",
    "minimumGuarantee": 300,
    "maxCapacity": 500,
    "rentPrice": 11000000,
    "baseRentPrice": 11000000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://apelgamo.com/home/wedding1",
    "naverMap": "https://map.naver.com/v5/search/아펠가모%20잠실",
    "memo": "공식 지점 확인",
    "zone": "송파",
    "tags": "컨벤션/모던",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 53,
    "name": "서울웨딩타워",
    "district": "송파구",
    "address": "서울 송파구 양재대로 932",
    "hallType": "컨벤션",
    "hallTone": "어두운홀",
    "ceremonyType": "분리",
    "ceremonyTime": "80",
    "hallCount": 1,
    "menu": "뷔페",
    "mealPrice": 95000,
    "mealStartPrice": 95000,
    "mealAveragePrice": 95000,
    "mealRange": "95000~110000",
    "minimumGuarantee": 350,
    "maxCapacity": 1000,
    "rentPrice": 10500000,
    "baseRentPrice": 10500000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://www.swtower.com/",
    "naverMap": "https://map.naver.com/v5/search/서울웨딩타워",
    "memo": "공식 사이트 확인",
    "zone": "송파",
    "tags": "컨벤션/대형",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 54,
    "name": "더컨벤션 잠실",
    "district": "송파구",
    "address": "서울 송파구 올림픽로 319",
    "hallType": "컨벤션",
    "hallTone": "혼합",
    "ceremonyType": "분리",
    "ceremonyTime": "80",
    "hallCount": 3,
    "menu": "뷔페",
    "mealPrice": 110000,
    "mealStartPrice": 110000,
    "mealAveragePrice": 110000,
    "mealRange": "110000",
    "minimumGuarantee": 300,
    "maxCapacity": 1000,
    "rentPrice": 12000000,
    "baseRentPrice": 12000000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "http://theconventionjs.iniwedding.com/",
    "naverMap": "https://map.naver.com/v5/search/더컨벤션%20잠실",
    "memo": "공식 운영/제휴 페이지",
    "zone": "송파",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 55,
    "name": "더컨벤션 송파문정",
    "district": "송파구",
    "address": "서울 송파구 송파대로 155",
    "hallType": "컨벤션",
    "hallTone": "어두운홀",
    "ceremonyType": "분리",
    "ceremonyTime": "80",
    "hallCount": 2,
    "menu": "뷔페",
    "mealPrice": 120000,
    "mealStartPrice": 120000,
    "mealAveragePrice": 120000,
    "mealRange": "120000",
    "minimumGuarantee": 300,
    "maxCapacity": 650,
    "rentPrice": 11000000,
    "baseRentPrice": 11000000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "http://theconvention.co.kr/sp/index.php",
    "naverMap": "https://map.naver.com/v5/search/더컨벤션%20송파문정",
    "memo": "공식 도메인 확인",
    "zone": "송파",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 56,
    "name": "루이비스 문정",
    "district": "송파구",
    "address": "서울 송파구 법원로 128",
    "hallType": "컨벤션",
    "hallTone": "어두운홀",
    "ceremonyType": "분리",
    "ceremonyTime": "80",
    "hallCount": 2,
    "menu": "뷔페",
    "mealPrice": 87000,
    "mealStartPrice": 87000,
    "mealAveragePrice": 87000,
    "mealRange": "87000",
    "minimumGuarantee": 300,
    "maxCapacity": 650,
    "rentPrice": 9500000,
    "baseRentPrice": 9500000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "",
    "subwayAccess": "#VALUE!",
    "homepage": "https://lvwedding.co.kr/new/m/index.html",
    "naverMap": "https://map.naver.com/v5/search/루이비스%20문정",
    "memo": "브랜드 공식",
    "zone": "송파",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 57,
    "name": "루벨",
    "district": "강동구",
    "address": "서울 강동구 천호대로 1102",
    "hallType": "컨벤션",
    "hallTone": "밝은홀",
    "ceremonyType": "분리",
    "ceremonyTime": "90",
    "hallCount": 1,
    "menu": "뷔페",
    "mealPrice": 107700,
    "mealStartPrice": 107700,
    "mealAveragePrice": 107700,
    "mealRange": "107700",
    "minimumGuarantee": 300,
    "maxCapacity": 600,
    "rentPrice": 10000000,
    "baseRentPrice": 10000000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "",
    "subwayAccess": "#VALUE!",
    "homepage": "",
    "naverMap": "https://map.naver.com/v5/search/루벨%20강동",
    "memo": "확인필요",
    "zone": "기타",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  },
  {
    "id": 60,
    "name": "스타시티아트홀 제2후보",
    "district": "광진구",
    "address": "서울 광진구 아차산로 262",
    "hallType": "컨벤션",
    "hallTone": "밝은홀",
    "ceremonyType": "분리",
    "ceremonyTime": "80",
    "hallCount": 1,
    "menu": "한식",
    "mealPrice": 95000,
    "mealStartPrice": 95000,
    "mealAveragePrice": 95000,
    "mealRange": "95000",
    "minimumGuarantee": 250,
    "maxCapacity": 700,
    "rentPrice": 9500000,
    "baseRentPrice": 9500000,
    "minimumRentPrice": null,
    "stylingPrice": null,
    "flowerPrice": null,
    "parking": "주차가능",
    "subwayAccess": "#VALUE!",
    "homepage": "https://starcityarthall.com/",
    "naverMap": "https://map.naver.com/v5/search/스타시티아트홀",
    "memo": "후보 복제용 슬롯",
    "zone": "기타",
    "tags": "",
    "budgetBand": "~2.5억",
    "recommendationGrade": "#VALUE!",
    "recommendationScore": "#VALUE!"
  }
];
